### ISSUE TITLE
How to test 1920*1080?

### ISSUE THREAD

**Issue by AlexZou14** [Abdullah-Abuolaim/defocus-deblurring-dual-pixel#13]
When we want to test the 1920 * 1080 image, the program shows that the input does not match

**Comment by Abdullah-Abuolaim** [comment]
The input should be a factor of 16, due to the 4 max pooling of stride 2 used in the UNet.
1920 is okay, but try to zero pad the 1080 to be 1088.
When I get some time, I will fix this in the code to check the input size, and automatically apply zero-padding if required.

Another way to go around this, is just to turn on the `resize` flag in the `config.py` file. This will resize the image to match instead of padding.
